apiVersion: v1
kind: Service
metadata:
  name: clientapi-service
spec:
  selector:
    app: clientapi-pod
  ports:
  - port: 30001
    name: grpc
    nodePort: 30001
    targetPort: 30001
  - port: 30021
    name: http
    nodePort: 30021
    targetPort: 30021
  type: LoadBalancer